export const users = [
    {
      firstName: "John",
      lastName: "Doe",
      username: "johndoe123",
      email: "johndoe@gmail.com",
      role: "Contributor",
      photoURL: "https://example.com/photos/johndoe.jpg",
      bio: "A passionate software developer with a love for open-source projects.",
      website: "https://johndoe.dev",
      profession: "Tech",
      expertise: "Intermediate",
    },
    {
      firstName: "Jane",
      lastName: "Smith",
      username: "janesmith",
      email: "janesmith@gmail.com",
      role: "Maintainer",
      photoURL: "https://example.com/photos/janesmith.jpg",
      bio: "A seasoned maintainer who enjoys mentoring and community-building.",
      website: "https://janesmith.com",
      profession: "Tech",
      expertise: "Expert",
    },
    {
      firstName: "Alice",
      lastName: "Johnson",
      username: "alicejohnson",
      email: "alicejohnson@gmail.com",
      role: "Contributor",
      photoURL: "https://example.com/photos/alicejohnson.jpg",
      bio: "A graphic designer venturing into the tech space.",
      website: "https://alicejohnson.design",
      profession: "Non-Tech",
      expertise: "Beginner",
    },
    {
      firstName: "Bob",
      lastName: "Brown",
      username: "bobbrown",
      email: "bobbrown@gmail.com",
      role: "Maintainer",
      photoURL: "https://example.com/photos/bobbrown.jpg",
      bio: "An expert in cloud computing with a knack for solving complex problems.",
      website: "https://bobbrown.tech",
      profession: "Tech",
      expertise: "Expert",
    },
    {
      firstName: "Charlie",
      lastName: "Davis",
      username: "charliedavis",
      email: "charliedavis@gmail.com",
      role: "Contributor",
      photoURL: "https://example.com/photos/charliedavis.jpg",
      bio: "A hobbyist developer and a full-time teacher exploring programming.",
      website: "https://charliedavis.blog",
      profession: "Non-Tech",
      expertise: "Intermediate",
    },
  ];
  
export const categories = ["Design", "Education", "Development", "Funding", "Security"];
export const tags = ["DeFi", "NFT", "dApps"];